# Clean up data using pandas

For this section of the project, I am cleaning mock data with pandas.

In [1]:
import pandas as pd

In [2]:
patients = pd.read_csv('vet_data.txt', header=None, sep='//', engine='python')

In [3]:
df = pd.DataFrame(patients)
df

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,Pet name;; owner name;; pet type;; pet dob,Fluffy;; Michael Scott;; cat;; 5/20/2019,Spots McGoo ;; Jan Levinson ;; dog;; 12/1/2...,Speedy ;; Ryan Howard ;; turtle ;; unknown,Gordon Gekko ;; Ryan Howard ;; turtle ;; unkn...,Winston Churchill ;; Pam Beesley ;; dog ...,Mr. Whiskers ;; Jim Halpert;; cat ;; 4/5/2018,Henrietta;; Dwight Shrute;; porcupine ;; u...,Sprinkles ;; Angela Martin ;; cat ;; 7/19/2000,Princess Lady;; Angela Martin ;; cat ;; 8/4/...,...,Mr. Ash ;; Angela Martin ;; cat ;; 6/1/2005,Phillip ;; Angela Martin;; cat ;; 3/20/2009,Bandit ;; Angela Martin ;; cat ;; 2/13/2016,Comstock ;; Angela Martin ;; cat ;; 10/03/2...,Lily ;; Stanley Hudson ;; dog ;; 8/8/2012,Ruth Bader Ginsberg ;; Oscar Martinez ;; dog ...,Neitzsche ;; Oscar Martinez ;; dog ;; 7/31/2015,Buster ;; Phyllis Vance ;; dog ;; 8/15/2010,Sadie ;; Meredith Palmer ;; cat ;; 1/15/2020,Wuphf ;; Kelly Kapoor ;; dog ;; 12/3/2018

In [4]:
df = df.replace(regex=r';;', value=',')
df

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,"Pet name, owner name, pet type, pet dob","Fluffy, Michael Scott, cat, 5/20/2019","Spots McGoo , Jan Levinson , dog, 12/1/2015","Speedy , Ryan Howard , turtle , unknown","Gordon Gekko , Ryan Howard , turtle , unknown","Winston Churchill , Pam Beesley , dog , ...","Mr. Whiskers , Jim Halpert, cat , 4/5/2018","Henrietta, Dwight Shrute, porcupine , unkn...","Sprinkles , Angela Martin , cat , 7/19/2000","Princess Lady, Angela Martin , cat , 8/4/2017",...,"Mr. Ash , Angela Martin , cat , 6/1/2005","Phillip , Angela Martin, cat , 3/20/2009","Bandit , Angela Martin , cat , 2/13/2016","Comstock , Angela Martin , cat , 10/03/2017","Lily , Stanley Hudson , dog , 8/8/2012","Ruth Bader Ginsberg , Oscar Martinez , dog , ...","Neitzsche , Oscar Martinez , dog , 7/31/2015","Buster , Phyllis Vance , dog , 8/15/2010","Sadie , Meredith Palmer , cat , 1/15/2020","Wuphf , Kelly Kapoor , dog , 12/3/2018"

In [5]:
row = []

for field in df:
    row.append(df[field].tolist())

print(row)

[['Pet name, owner name, pet type, pet dob '], [' Fluffy, Michael Scott, cat, 5/20/2019 '], [' Spots McGoo  , Jan  Levinson , dog, 12/1/2015 '], [' Speedy   , Ryan Howard , turtle , unknown '], [' Gordon Gekko , Ryan Howard , turtle , unknown '], [' Winston Churchill ,   Pam   Beesley , dog  , 3/30/2009 '], [' Mr. Whiskers  , Jim Halpert, cat , 4/5/2018 '], [' Henrietta, Dwight   Shrute, porcupine  , unknown '], [' Sprinkles , Angela Martin  , cat , 7/19/2000 '], [' Princess Lady, Angela Martin  , cat , 8/4/2017 '], ['  Ember , Angela Martin  , cat , 4/3/2015 '], ['   Milky Way , Angela Martin  , cat , 11/15/2012 '], [' Diane, Angela Martin , cat   , 9/21/2015 '], [' Lumpy  ,  Angela  Martin  , cat , 02/07/2012 '], [' Petals , Angela Martin  , cat , 10/31/2010 '], [' Mr. Ash , Angela Martin , cat , 6/1/2005 '], [' Phillip ,   Angela Martin, cat , 3/20/2009 '], [' Bandit , Angela Martin , cat , 2/13/2016 '], [' Comstock   , Angela Martin , cat , 10/03/2017 '], [' Lily , Stanley Hudson , dog , 8/8/2012 '], [' Ruth Bader Ginsberg , Oscar Martinez , dog , 9/1/2016 '], [' Neitzsche , Oscar Martinez , dog , 7/31/2015 '], [' Buster , Phyllis Vance , dog , 8/15/2010 '], [' Sadie , Meredith Palmer , cat , 1/15/2020 '], [' Wuphf , Kelly Kapoor   , dog  , 12/3/2018']]

In [6]:
patients = pd.DataFrame(row)

patients

                                                    0
0            Pet name, owner name, pet type, pet dob
1              Fluffy, Michael Scott, cat, 5/20/2019
2      Spots McGoo  , Jan  Levinson , dog, 12/1/2015
3          Speedy   , Ryan Howard , turtle , unknown
4      Gordon Gekko , Ryan Howard , turtle , unknown
5    Winston Churchill ,   Pam   Beesley , dog  , ...
6        Mr. Whiskers  , Jim Halpert, cat , 4/5/2018
7    Henrietta, Dwight   Shrute, porcupine  , unkn...
8       Sprinkles , Angela Martin  , cat , 7/19/2000
9     Princess Lady, Angela Martin  , cat , 8/4/2017
10           Ember , Angela Martin  , cat , 4/3/2015
11     Milky Way , Angela Martin  , cat , 11/15/2012
12          Diane, Angela Martin , cat   , 9/21/2015
13      Lumpy  ,  Angela  Martin  , cat , 02/07/2012
14        Petals , Angela Martin  , cat , 10/31/2010
15          Mr. Ash , Angela Martin , cat , 6/1/2005
16        Phillip ,   Angela Martin, cat , 3/20/2009
17          Bandit , Angela Martin , cat , 2/13/2016
18     Comstock   , Angela Martin , cat , 10/03/2017
19            Lily , Stanley Hudson , dog , 8/8/2012
20   Ruth Bader Ginsberg , Oscar Martinez , dog , ...
21      Neitzsche , Oscar Martinez , dog , 7/31/2015
22          Buster , Phyllis Vance , dog , 8/15/2010
23         Sadie , Meredith Palmer , cat , 1/15/2020
24          Wuphf , Kelly Kapoor   , dog  , 12/3/2018

In [7]:
patients = patients[0].str.split(',', expand=True)

patients

                        0                   1             2             3
0                Pet name          owner name      pet type      pet dob
1                  Fluffy       Michael Scott           cat    5/20/2019
2           Spots McGoo        Jan  Levinson            dog    12/1/2015
3               Speedy           Ryan Howard        turtle       unknown
4           Gordon Gekko         Ryan Howard        turtle       unknown
5      Winston Churchill       Pam   Beesley          dog      3/30/2009
6          Mr. Whiskers           Jim Halpert          cat      4/5/2018
7               Henrietta     Dwight   Shrute   porcupine        unknown
8              Sprinkles      Angela Martin            cat     7/19/2000
9           Princess Lady     Angela Martin            cat      8/4/2017
10                 Ember      Angela Martin            cat      4/3/2015
11             Milky Way      Angela Martin            cat    11/15/2012
12                  Diane      Angela Martin         cat       9/21/2015
13                Lumpy      Angela  Martin            cat    02/07/2012
14                Petals      Angela Martin            cat    10/31/2010
15               Mr. Ash       Angela Martin           cat      6/1/2005
16               Phillip        Angela Martin          cat     3/20/2009
17                Bandit       Angela Martin           cat     2/13/2016
18            Comstock         Angela Martin           cat    10/03/2017
19                  Lily      Stanley Hudson           dog      8/8/2012
20   Ruth Bader Ginsberg      Oscar Martinez           dog      9/1/2016
21             Neitzsche      Oscar Martinez           dog     7/31/2015
22                Buster       Phyllis Vance           dog     8/15/2010
23                 Sadie     Meredith Palmer           cat     1/15/2020
24                 Wuphf      Kelly Kapoor            dog       12/3/2018

In [8]:
headers = patients.iloc[0]
patients = patients[1:]
patients.columns = headers

patients

0                Pet name          owner name      pet type      pet dob
1                  Fluffy       Michael Scott           cat    5/20/2019
2           Spots McGoo        Jan  Levinson            dog    12/1/2015
3               Speedy           Ryan Howard        turtle       unknown
4           Gordon Gekko         Ryan Howard        turtle       unknown
5      Winston Churchill       Pam   Beesley          dog      3/30/2009
6          Mr. Whiskers           Jim Halpert          cat      4/5/2018
7               Henrietta     Dwight   Shrute   porcupine        unknown
8              Sprinkles      Angela Martin            cat     7/19/2000
9           Princess Lady     Angela Martin            cat      8/4/2017
10                 Ember      Angela Martin            cat      4/3/2015
11             Milky Way      Angela Martin            cat    11/15/2012
12                  Diane      Angela Martin         cat       9/21/2015
13                Lumpy      Angela  Martin            cat    02/07/2012
14                Petals      Angela Martin            cat    10/31/2010
15               Mr. Ash       Angela Martin           cat      6/1/2005
16               Phillip        Angela Martin          cat     3/20/2009
17                Bandit       Angela Martin           cat     2/13/2016
18            Comstock         Angela Martin           cat    10/03/2017
19                  Lily      Stanley Hudson           dog      8/8/2012
20   Ruth Bader Ginsberg      Oscar Martinez           dog      9/1/2016
21             Neitzsche      Oscar Martinez           dog     7/31/2015
22                Buster       Phyllis Vance           dog     8/15/2010
23                 Sadie     Meredith Palmer           cat     1/15/2020
24                 Wuphf      Kelly Kapoor            dog       12/3/2018

In [9]:
patients.columns

Index(['Pet name', ' owner name', ' pet type', ' pet dob '], dtype='object', name=0)

In [10]:
patients.columns = patients.columns.str.strip()

In [11]:
patients.columns

Index(['Pet name', 'owner name', 'pet type', 'pet dob'], dtype='object', name=0)

In [12]:
patients = patients.rename({'Pet name': 'pet', 'owner name': 'owner', 'pet type': 'type', 'pet dob': 'dob'}, axis=1)

In [13]:
patients

0                     pet               owner          type           dob
1                  Fluffy       Michael Scott           cat    5/20/2019
2           Spots McGoo        Jan  Levinson            dog    12/1/2015
3               Speedy           Ryan Howard        turtle       unknown
4           Gordon Gekko         Ryan Howard        turtle       unknown
5      Winston Churchill       Pam   Beesley          dog      3/30/2009
6          Mr. Whiskers           Jim Halpert          cat      4/5/2018
7               Henrietta     Dwight   Shrute   porcupine        unknown
8              Sprinkles      Angela Martin            cat     7/19/2000
9           Princess Lady     Angela Martin            cat      8/4/2017
10                 Ember      Angela Martin            cat      4/3/2015
11             Milky Way      Angela Martin            cat    11/15/2012
12                  Diane      Angela Martin         cat       9/21/2015
13                Lumpy      Angela  Martin            cat    02/07/2012
14                Petals      Angela Martin            cat    10/31/2010
15               Mr. Ash       Angela Martin           cat      6/1/2005
16               Phillip        Angela Martin          cat     3/20/2009
17                Bandit       Angela Martin           cat     2/13/2016
18            Comstock         Angela Martin           cat    10/03/2017
19                  Lily      Stanley Hudson           dog      8/8/2012
20   Ruth Bader Ginsberg      Oscar Martinez           dog      9/1/2016
21             Neitzsche      Oscar Martinez           dog     7/31/2015
22                Buster       Phyllis Vance           dog     8/15/2010
23                 Sadie     Meredith Palmer           cat     1/15/2020
24                 Wuphf      Kelly Kapoor            dog       12/3/2018